#!/usr/bin/env python3
"""Generate the site homepage (docs/zh/index.md, docs/en/index.md).

Replaces the old hand-written demo homepage with a real product directory:
one card per product, each card listing links to the documents that actually
exist in the built site.

Design notes
------------
- Standard library only (same constraint as generate_llms_txt.py).
- Reuses generate_llms_txt.collect() so homepage and llms.txt can never
  disagree about what documents exist.
- Skips categories excluded from the mkdocs build (Datasheets,
  Certification Documents, Drawings) and stray md under images/ —
  linking to them would produce 404s on the published site.
- Links point at the built *.html twins (use_directory_urls: false) and
  are percent-encoded so they survive spaces / CJK in paths.
- Output is deterministic: same content -> byte-identical file.

Usage
-----
    python scripts/generate_home_index.py            # writes both langs
    python scripts/generate_home_index.py --lang zh
    python scripts/generate_home_index.py --check    # non-zero exit if stale
"""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path
from urllib.parse import quote

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_llms_txt import DOCS_DIR, REPO_ROOT, collect, parse_version

# Categories excluded from the mkdocs build (see `plugins: exclude` in
# mkdocs.yml) — their pages do not exist on the published site.
EXCLUDED_CATEGORIES = {"datasheets", "certification documents", "drawings"}

PAGE_META = {
    "zh": {
        "frontmatter_title": "文档站点",
        "title": "映翰通产品文档",
        "subtitle": "产品手册、开发文档与解决方案",
        "search_placeholder": "搜索所有文档",
        "search_aria": "搜索所有文档",
        "no_results": "没有找到符合条件的结果",
        "results_suffix": " 个符合条件的结果",
    },
    "en": {
        "frontmatter_title": "Documentation",
        "title": "InHand Product Documentation",
        "subtitle": "Product manuals, developer documentation and solutions",
        "search_placeholder": "Search all documents",
        "search_aria": "Search all documents",
        "no_results": "No matching results",
        "results_suffix": " matching result(s)",
    },
}

GENERATED_MARKER = (
    "<!-- AUTO-GENERATED by scripts/generate_home_index.py — do not edit by hand. -->"
)


def doc_label(doc) -> str:
    """Short link label: subcategory (falling back to category) + version."""
    base = doc.subcategory or doc.category or doc.title
    # The card is already titled with the product name — drop the
    # redundant prefix from title-derived labels ("ER805 认证证书" -> "认证证书").
    if base == doc.title and base.startswith(doc.product + " "):
        base = base[len(doc.product) + 1:]
    version = parse_version(doc.link)
    return f"{base} V{version}" if version else base


def build_cards(lang: str) -> str:
    docs = collect(lang, base_url=None)
    visible = [
        d for d in docs
        if d.category.lower() not in EXCLUDED_CATEGORIES
        and "/images/" not in d.link
    ]

    by_product: dict[str, list] = {}
    for d in visible:
        by_product.setdefault(d.product, []).append(d)

    cards: list[str] = []
    # Secondary key breaks the tie between case-variant product dirs
    # (e.g. "MO 68A" vs "Mo 68A") identically on all platforms.
    for product in sorted(by_product, key=lambda p: (p.lower(), p)):
        group = sorted(by_product[product], key=lambda d: (d.category, d.subcategory, d.link))
        labels = [doc_label(d) for d in group]
        items = []
        for d, raw_label in zip(group, labels):
            href = quote(d.link[: -len(".md")] + ".html", safe="/")
            # Duplicate labels within one product (e.g. two FlexAPI docs)
            # are indistinguishable — fall back to the document title.
            label = html.escape(d.title if labels.count(raw_label) > 1 else raw_label)
            title_attr = html.escape(d.title, quote=True)
            items.append(
                f'        <li><a href="{href}" title="{title_attr}">{label}</a></li>'
            )
        cards.append(
            '    <div class="pm-card">\n'
            '      <div class="pm-card__body">\n'
            f'        <div class="pm-card__title">{html.escape(product)}</div>\n'
            '        <ul class="pm-card__links">\n'
            + "\n".join(items) + "\n"
            "        </ul>\n"
            "      </div>\n"
            "    </div>"
        )
    return "\n".join(cards)


PAGE_TEMPLATE = """---
title: @@FRONT_TITLE@@
hide:
  - navigation
  - toc
---

@@MARKER@@

<div class="pm-home">
  <h1 class="pm-home__title">@@TITLE@@</h1>
  <p class="pm-home__subtitle">@@SUBTITLE@@</p>

  <div class="pm-home__search">
    <div class="pm-home-search" role="search" aria-label="@@ARIA@@">
      <span class="pm-home-search__icon" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
          <path fill="currentColor" d="M9.5 3A6.5 6.5 0 0 1 16 9.5c0 1.61-.59 3.09-1.57 4.23l.27.27h.8l5 5-1.5 1.5-5-5v-.8l-.27-.27A6.48 6.48 0 0 1 9.5 16 6.5 6.5 0 1 1 9.5 3m0 2A4.5 4.5 0 1 0 14 9.5 4.5 4.5 0 0 0 9.5 5Z"/>
        </svg>
      </span>
      <input class="pm-home-search__input" id="pm-home-search-input" type="search" placeholder="@@PLACEHOLDER@@" autocomplete="off" />
      <span class="pm-home-search__hint">Ctrl K</span>
    </div>
  </div>

  <div class="pm-home-search__results" id="pm-home-search-results" aria-live="polite" style="display:none"></div>

  <div class="pm-home__grid">
@@CARDS@@
  </div>
</div>

<style>
  .pm-home {
    max-width: 64rem;
    margin: 0 auto;
    padding: 1.25rem 1rem 2rem;
  }
  .pm-home__title {
    text-align: center;
    font-size: clamp(2rem, 4vw, 3rem);
    margin: 0.75rem 0 0.25rem;
    letter-spacing: -0.02em;
  }
  .pm-home__subtitle {
    text-align: center;
    margin: 0 0 1.25rem;
    color: var(--md-default-fg-color--light);
  }

  .pm-home__search {
    display: flex;
    justify-content: center;
    margin: 1rem 0 1.25rem;
  }
  .pm-home-search {
    width: min(56rem, 92vw);
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.65rem 1rem;
    border-radius: 999px;
    border: 2px solid color-mix(in srgb, var(--md-primary-fg-color) 65%, var(--md-default-bg-color));
    background: color-mix(in srgb, var(--md-primary-fg-color) 8%, var(--md-default-bg-color));
    color: var(--md-default-fg-color);
    box-shadow: 0 6px 18px rgba(0,0,0,.08);
    transition: box-shadow 120ms ease, border-color 120ms ease, transform 120ms ease, background 120ms ease;
  }
  .pm-home-search:hover {
    transform: translateY(-1px);
    box-shadow: 0 10px 26px rgba(0,0,0,.12);
  }
  .pm-home-search:focus-within {
    border-color: var(--md-primary-fg-color);
    box-shadow: 0 0 0 3px color-mix(in srgb, var(--md-primary-fg-color) 25%, transparent), 0 10px 26px rgba(0,0,0,.12);
    background: var(--md-default-bg-color);
    transform: translateY(-1px);
  }
  .pm-home-search__icon svg {
    width: 1.3rem;
    height: 1.3rem;
    color: var(--md-default-fg-color--light);
  }
  .pm-home-search__input {
    flex: 1;
    border: none;
    outline: none;
    background: transparent;
    color: var(--md-default-fg-color);
    font-size: 1.05rem;
    line-height: 1.6;
  }
  .pm-home-search__input::placeholder {
    color: var(--md-default-fg-color--light);
  }
  .pm-home-search__hint {
    padding: 0.15rem 0.5rem;
    border-radius: 0.5rem;
    border: 1px solid var(--md-default-fg-color--lightest);
    background: var(--md-default-bg-color);
    color: var(--md-default-fg-color--light);
    font-size: 0.8rem;
    line-height: 1.4;
  }

  .pm-home-search__results {
    width: min(56rem, 92vw);
    margin: 0 auto 1.25rem;
    border: 1px solid var(--md-default-fg-color--lightest);
    border-radius: 0.8rem;
    background: var(--md-default-bg-color);
    overflow: hidden;
    box-shadow: 0 14px 34px rgba(0,0,0,.10);
  }
  .pm-home-search__meta {
    padding: 0.7rem 1rem;
    color: var(--md-default-fg-color--light);
    border-bottom: 1px solid var(--md-default-fg-color--lightest);
    font-size: 0.9rem;
  }
  .pm-home-search__item {
    display: flex;
    gap: 0.75rem;
    padding: 0.9rem 1rem;
    text-decoration: none;
    color: var(--md-default-fg-color);
    border-top: 1px solid var(--md-default-fg-color--lightest);
  }
  .pm-home-search__item:first-of-type { border-top: none; }
  .pm-home-search__item:hover {
    background: color-mix(in srgb, var(--md-primary-fg-color) 8%, transparent);
  }
  .pm-home-search__itemicon svg {
    width: 1.3rem;
    height: 1.3rem;
    color: var(--md-default-fg-color--light);
    margin-top: 0.2rem;
  }
  .pm-home-search__itemtitle {
    font-weight: 800;
    margin-bottom: 0.25rem;
    font-size: 1.05rem;
  }
  .pm-home-search__itemdesc {
    color: var(--md-default-fg-color--light);
    line-height: 1.45;
  }
  .pm-home-search__hit {
    color: var(--md-primary-fg-color);
    font-weight: 800;
  }

  .pm-home__grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 1rem;
    margin-top: 1.5rem;
  }
  @media (max-width: 60rem) {
    .pm-home__grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  }
  @media (max-width: 38rem) {
    .pm-home__grid { grid-template-columns: 1fr; }
  }
  .pm-card {
    display: flex;
    gap: 1rem;
    padding: 1rem;
    border-radius: 0.9rem;
    background: var(--md-default-bg-color);
    border: 1px solid var(--md-default-fg-color--lightest);
    color: var(--md-default-fg-color);
    transition: transform 120ms ease, box-shadow 120ms ease, border-color 120ms ease;
  }
  .pm-card:hover {
    transform: translateY(-2px);
    border-color: color-mix(in srgb, var(--md-primary-fg-color) 35%, var(--md-default-fg-color--lightest));
    box-shadow: 0 12px 28px rgba(0,0,0,.10);
  }
  .pm-card__body { min-width: 0; }
  .pm-card__title {
    font-weight: 800;
    margin: 0.05rem 0 0.4rem;
    letter-spacing: -0.01em;
  }
  .pm-card__links {
    list-style: none;
    margin: 0;
    padding: 0;
  }
  .pm-card__links li {
    margin: 0.15rem 0;
    line-height: 1.45;
  }
  .pm-card__links a {
    color: var(--md-typeset-a-color, var(--md-primary-fg-color));
    text-decoration: none;
    font-size: 0.95rem;
    overflow-wrap: anywhere;
  }
  .pm-card__links a:hover {
    text-decoration: underline;
  }
</style>

<script>
  (function () {
    var INDEX_URL = "search/search_index.json";
    var state = { index: null, ready: false };

    function norm(s) {
      return (s || "").toString().trim().toLowerCase();
    }

    function escapeHtml(text) {
      return (text || "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
    }

    function highlight(text, needle) {
      var safe = escapeHtml(text);
      if (!needle) return safe;
      var re = new RegExp(needle.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&"), "ig");
      return safe.replace(re, function (m) {
        return '<span class="pm-home-search__hit">' + m + "</span>";
      });
    }

    function pickSnippet(text, needle) {
      var raw = (text || "").replace(/\\s+/g, " ").trim();
      if (!raw) return "";
      if (!needle) return raw.slice(0, 90);
      var idx = raw.toLowerCase().indexOf(needle);
      if (idx < 0) return raw.slice(0, 90);
      var start = Math.max(0, idx - 28);
      var end = Math.min(raw.length, idx + needle.length + 60);
      var prefix = start > 0 ? "…" : "";
      var suffix = end < raw.length ? "…" : "";
      return prefix + raw.slice(start, end) + suffix;
    }

    function ensureIndex() {
      if (state.ready) return Promise.resolve(state.index);
      return fetch(INDEX_URL, { credentials: "same-origin" })
        .then(function (r) { return r.json(); })
        .then(function (data) {
          state.index = data || {};
          state.ready = true;
          return state.index;
        })
        .catch(function () {
          state.ready = true;
          state.index = { docs: [] };
          return state.index;
        });
    }

    function searchDocs(q) {
      var needle = norm(q);
      if (!needle) return [];
      var docs = (state.index && state.index.docs) ? state.index.docs : [];
      var res = [];
      for (var i = 0; i < docs.length; i++) {
        var d = docs[i] || {};
        var title = (d.title || d.location || "").toString();
        var text = (d.text || "").toString();
        var hay = norm(title + " " + text);
        var pos = hay.indexOf(needle);
        if (pos >= 0) {
          res.push({ title: title, location: d.location || "", text: text, score: pos });
        }
      }
      res.sort(function (a, b) { return a.score - b.score; });
      return res.slice(0, 8);
    }

    function renderResults(container, query, items) {
      container.innerHTML = "";
      if (!query.trim()) {
        container.style.display = "none";
        return;
      }
      var header = document.createElement("div");
      header.className = "pm-home-search__meta";
      if (!items.length) {
        header.textContent = "@@NO_RESULTS@@";
      } else {
        header.textContent = items.length + "@@RESULTS_SUFFIX@@";
      }
      container.appendChild(header);

      if (items.length) {
        for (var i = 0; i < items.length; i++) {
          var it = items[i];
          var a = document.createElement("a");
          a.className = "pm-home-search__item";
          a.href = it.location || "#";
          a.innerHTML =
            '<span class="pm-home-search__itemicon" aria-hidden="true">' +
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="currentColor" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6m4 18H6V4h7v5h5v11z"/></svg>' +
            "</span>" +
            '<div class="pm-home-search__itembody">' +
            '<div class="pm-home-search__itemtitle">' + highlight(it.title || it.location, norm(query)) + "</div>" +
            '<div class="pm-home-search__itemdesc">' + highlight(pickSnippet(it.text, norm(query)), norm(query)) + "</div>" +
            "</div>";
          container.appendChild(a);
        }
      }
      container.style.display = "";
    }

    function bootSearch() {
      var input = document.getElementById("pm-home-search-input");
      var results = document.getElementById("pm-home-search-results");
      if (!input || !results || input.dataset.bound === "true") return;
      input.dataset.bound = "true";

      ensureIndex();

      input.addEventListener("input", function () {
        ensureIndex().then(function () {
          var items = searchDocs(input.value);
          renderResults(results, input.value, items);
        });
      });

      input.addEventListener("keydown", function (e) {
        if ((e.ctrlKey || e.metaKey) && (e.key === "k" || e.key === "K")) {
          e.preventDefault();
          input.focus();
          input.select();
        }
        if (e.key === "Escape") {
          input.value = "";
          results.style.display = "none";
          input.blur();
        }
      });

      document.addEventListener("click", function (e) {
        if (!results.contains(e.target) && e.target !== input) {
          results.style.display = "none";
        }
      });
    }

    document.addEventListener("DOMContentLoaded", bootSearch);
    document.addEventListener("navigation:complete", bootSearch);
    var doc$ = window.document$;
    if (doc$ && typeof doc$.subscribe === "function") {
      doc$.subscribe(function () { requestAnimationFrame(bootSearch); });
    }
  })();
</script>
"""


def render(lang: str) -> str:
    meta = PAGE_META[lang]
    return (PAGE_TEMPLATE
            .replace("@@FRONT_TITLE@@", meta["frontmatter_title"])
            .replace("@@MARKER@@", GENERATED_MARKER)
            .replace("@@TITLE@@", html.escape(meta["title"]))
            .replace("@@SUBTITLE@@", html.escape(meta["subtitle"]))
            .replace("@@ARIA@@", meta["search_aria"])
            .replace("@@PLACEHOLDER@@", meta["search_placeholder"])
            .replace("@@NO_RESULTS@@", meta["no_results"])
            .replace("@@RESULTS_SUFFIX@@", meta["results_suffix"])
            .replace("@@CARDS@@", build_cards(lang)))


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate homepage index.md files.")
    ap.add_argument("--lang", choices=["en", "zh"], action="append",
                    help="Limit to given language(s); default both.")
    ap.add_argument("--check", action="store_true",
                    help="Do not write; exit non-zero if any homepage is stale.")
    args = ap.parse_args()

    langs = args.lang or ["en", "zh"]
    stale = False
    for lang in langs:
        lang_root = DOCS_DIR / lang
        if not lang_root.is_dir():
            print(f"skip {lang}: {lang_root} not found", file=sys.stderr)
            continue
        content = render(lang)
        out = lang_root / "index.md"
        if args.check:
            existing = out.read_text(encoding="utf-8") if out.exists() else ""
            if existing != content:
                stale = True
                print(f"STALE: {out.relative_to(REPO_ROOT).as_posix()}")
            continue
        # newline="\n": identical output on Windows and CI (Linux)
        out.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(REPO_ROOT).as_posix()}")

    if args.check and stale:
        print("homepage is out of date; run scripts/generate_home_index.py",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
