#!/usr/bin/env python3
"""Generate per-product certification and drawing registry pages.

Certification Documents/ and Drawings/ are excluded from the mkdocs build
(binary PDFs / STP models, served from cloud storage), so neither the site
nor AI crawlers can discover them.  This script writes, for every product
that has such assets, small markdown registry pages *outside* the excluded
directories:

    docs/{lang}/{Product}/certifications.md   — which standards, file links
    docs/{lang}/{Product}/drawings.md         — 2D/3D drawing file links

The pages carry frontmatter (title/description), so the llms.txt and
homepage generators pick them up automatically.  Original files are linked
via GitHub blob URLs — they are not published on the static site.

Per-tree: each language's registry lists only the assets present in that
language's own tree (docs/zh certs for the CN site, docs/en certs for the
overseas site) — certifications are region-specific, so they are placed
per market upstream.  A registry page is written only when that product
actually has assets in that tree; products with none get no page, and any
previously-generated page whose backing files are gone is removed.

Standard library only; deterministic output (LF, sorted); --check mode.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"
GITHUB_BLOB_BASE = "https://github.com/inhandnet/documents/blob/master/"

GENERATED_MARKER = (
    "<!-- AUTO-GENERATED by scripts/generate_asset_pages.py — do not edit by hand. -->"
)

CERT_DIR = "certification documents"
DRAWINGS_DIR = "drawings"

TEXT = {
    "zh": {
        "cert_title": "{product} 认证证书",
        "cert_description": "{product} 已获认证清单（{standards}），含证书原件文件链接",
        "cert_intro": (
            "本页登记 {product} 的认证证书原件。原件为 PDF/压缩包，"
            "存放在文档仓库中，点击链接查看或下载。"
        ),
        "cert_columns": "| 认证/标准 | 文件 | 原件 |",
        "drawing_title": "{product} 结构图纸",
        "drawing_description": "{product} 结构图纸登记（{kinds}），含图纸原件文件链接",
        "drawing_intro": (
            "本页登记 {product} 的结构图纸。2D 图纸为 PDF，3D 模型为 STP，"
            "存放在文档仓库中，点击链接查看或下载。"
        ),
        "drawing_columns": "| 类型 | 文件 | 原件 |",
        "view": "查看",
    },
    "en": {
        "cert_title": "{product} Certifications",
        "cert_description": "{product} certification list ({standards}) with links to the original certificate files",
        "cert_intro": (
            "This page registers the certification files for {product}. "
            "Originals are PDF / archive files stored in the documentation "
            "repository; follow the links to view or download."
        ),
        "cert_columns": "| Standard | File | Original |",
        "drawing_title": "{product} Drawings",
        "drawing_description": "{product} mechanical drawings ({kinds}) with links to the original drawing files",
        "drawing_intro": (
            "This page registers the mechanical drawings for {product}. "
            "2D drawings are PDF, 3D models are STP, stored in the "
            "documentation repository; follow the links to view or download."
        ),
        "drawing_columns": "| Type | File | Original |",
        "view": "View",
    },
}


def git_files() -> list[str]:
    out = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files", "-z", "--", "docs/"],
        capture_output=True, check=True,
    ).stdout.decode("utf-8")
    return sorted(p for p in out.split("\0") if p)


def scan(files: list[str]):
    """Return (certs, drawings, product_dirs).

    certs[lang][product] = [(standard, filename, repo_path), ...]
    drawings[lang][product] = [(kind, filename, repo_path), ...]
    product_dirs[lang] = {product, ...}
    """
    certs: dict = {"en": {}, "zh": {}}
    drawings: dict = {"en": {}, "zh": {}}
    product_dirs: dict = {"en": set(), "zh": set()}

    for path in files:
        parts = path.split("/")
        # docs / lang / Product / Category / ...
        if len(parts) < 4 or parts[0] != "docs" or parts[1] not in ("en", "zh"):
            continue
        lang, product, category = parts[1], parts[2], parts[3]
        product_dirs[lang].add(product)
        if category.lower() == CERT_DIR and len(parts) >= 6:
            standard = parts[4]
            certs[lang].setdefault(product, []).append((standard, parts[-1], path))
        elif category.lower() == DRAWINGS_DIR and len(parts) >= 6:
            kind = parts[4]
            drawings[lang].setdefault(product, []).append((kind, parts[-1], path))
    return certs, drawings, product_dirs


def assets_for_lang(assets: dict, lang: str) -> dict:
    """Asset lists for one language, from that language's own tree only.

    Certifications/drawings are region-specific and placed per market
    upstream (docs/zh for CN, docs/en for overseas), so no cross-tree
    merge: a product only appears if it has assets in this tree.
    """
    return {p: sorted(v) for p, v in assets[lang].items() if v}


def blob_link(repo_path: str) -> str:
    return GITHUB_BLOB_BASE + quote(repo_path, safe="/")


def render_page(lang: str, product: str, kind: str, items: list) -> str:
    t = TEXT[lang]
    groups = sorted({i[0] for i in items})
    if kind == "cert":
        title = t["cert_title"].format(product=product)
        description = t["cert_description"].format(
            product=product, standards="、".join(groups) if lang == "zh" else ", ".join(groups))
        intro = t["cert_intro"].format(product=product)
        columns = t["cert_columns"]
    else:
        title = t["drawing_title"].format(product=product)
        description = t["drawing_description"].format(
            product=product, kinds="、".join(groups) if lang == "zh" else ", ".join(groups))
        intro = t["drawing_intro"].format(product=product)
        columns = t["drawing_columns"]

    lines = [
        "---",
        f'title: "{title}"',
        f'description: "{description}"',
        "---",
        "",
        GENERATED_MARKER,
        "",
        f"# {title}",
        "",
        intro,
        "",
        columns,
        "|---|---|---|",
    ]
    for group, filename, repo_path in sorted(items):
        lines.append(f"| {group} | {filename} | [{t['view']}]({blob_link(repo_path)}) |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate per-product certification/drawing registry pages.")
    ap.add_argument("--lang", choices=["en", "zh"], action="append",
                    help="Limit to given language(s); default both.")
    ap.add_argument("--check", action="store_true",
                    help="Do not write; exit non-zero if any page is stale or missing.")
    args = ap.parse_args()

    langs = args.lang or ["en", "zh"]
    files = git_files()
    certs, drawings, product_dirs = scan(files)

    stale = False
    written = 0
    removed = 0
    for lang in langs:
        for kind, assets, filename in (
            ("cert", assets_for_lang(certs, lang), "certifications.md"),
            ("drawing", assets_for_lang(drawings, lang), "drawings.md"),
        ):
            # pages we should have for this (lang, kind) after this run
            expected = set()
            for product, items in sorted(assets.items()):
                out = DOCS_DIR / lang / product / filename
                expected.add(out)
                content = render_page(lang, product, kind, items)
                if args.check:
                    existing = out.read_text(encoding="utf-8") if out.exists() else ""
                    if existing != content:
                        stale = True
                        print(f"STALE: {out.relative_to(REPO_ROOT).as_posix()}")
                    continue
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(content, encoding="utf-8", newline="\n")
                written += 1

            # remove orphaned generated pages whose backing files are gone
            lang_dir = DOCS_DIR / lang
            if lang_dir.is_dir():
                for existing_page in sorted(lang_dir.glob(f"*/{filename}")):
                    if existing_page in expected:
                        continue
                    if GENERATED_MARKER not in existing_page.read_text(encoding="utf-8"):
                        continue  # never touch a hand-authored file
                    rel = existing_page.relative_to(REPO_ROOT).as_posix()
                    if args.check:
                        stale = True
                        print(f"ORPHAN: {rel}")
                    else:
                        existing_page.unlink()
                        removed += 1

    if args.check:
        if stale:
            print("asset pages out of date; run scripts/generate_asset_pages.py",
                  file=sys.stderr)
            return 1
        return 0
    print(f"wrote {written} asset registry page(s), removed {removed} orphan(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
