#!/usr/bin/env python3
"""由 data/eol-products.{zh,en}.md 生成文档站上的 EOL 页面。

    data/eol-products.zh.md  ->  docs/zh/EOL Products/EOL Products.md
    data/eol-products.en.md  ->  docs/en/EOL Products/EOL Products.md

生成的页面进 MkDocs 站点、md 孪生版和 llms.txt（llms.txt 只收录语言根下
二级及更深的文件，所以必须放在目录里，不能是语言根下的散文件）。

只用标准库；确定性输出（无时间戳、固定排序），重复跑不产生 diff。

用法：
    python scripts/generate_eol_pages.py
    python scripts/generate_eol_pages.py --check   # 内容过期则非零退出
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List

sys.path.insert(0, str(Path(__file__).resolve().parent))
from eol_data import (  # noqa: E402
    COLUMN_TITLES,
    FIELDS,
    REPO_ROOT,
    SITES,
    EolDataError,
    load_entries,
)

PAGE_DIR = "EOL Products"
PAGE_NAME = "EOL Products.md"

TITLES = {
    "zh": "EOL 产品清单",
    "en": "EOL Product List",
}
DESCRIPTIONS = {
    "zh": "映翰通已进入生命周期终止（EOL）阶段的产品清单，含替代产品系列与停止订购、停止生产、停止支持日期",
    "en": "InHand Networks end-of-life (EOL) products with their replacement series and end-of-ordering, end-of-production and end-of-support dates",
}
INTROS = {
    "zh": (
        "映翰通（InHand Networks）已正式宣布下列产品进入生命周期终止（EOL）阶段。"
        "请参考「替代产品系列」提前规划替换，以保障业务连续性。\n\n"
        "- **停止订购日期**：该日期之后不再接受订单。\n"
        "- **停止生产日期**：该日期之后不再生产。\n"
        "- **停止支持日期**：该日期之后不再提供任何形式的技术支持或维护服务。\n\n"
        "官网同款清单见 <https://www.inhand.com.cn/support/eol-products>。"
        "本页与官网由同一份数据自动生成，映翰通保留随时更新本信息的权利。"
    ),
    "en": (
        "InHand Networks has announced end-of-life (EOL) for the products below. "
        "Please plan replacements with the listed successor series to keep your "
        "deployments supported.\n\n"
        "- **End of Ordering** — no orders accepted after this date.\n"
        "- **End of Production** — no units manufactured after this date.\n"
        "- **End of Support** — no technical support or maintenance after this date.\n\n"
        "The same list is published at <https://www.inhand.com/en/support/eol-products>. "
        "Both are generated from one source; InHand Networks reserves the right to "
        "update this information at any time."
    ),
}


def page_path(site: str) -> Path:
    return REPO_ROOT / "docs" / site / PAGE_DIR / PAGE_NAME


def render(site: str) -> str:
    entries = load_entries(site)
    headers = COLUMN_TITLES[site]

    lines: List[str] = [
        "---",
        f"title: {TITLES[site]}",
        f"description: {DESCRIPTIONS[site]}",
        "---",
        "",
        "<!-- AUTO-GENERATED from data/eol-products.%s.md by scripts/generate_eol_pages.py." % site,
        "     Do not edit this file; edit the data file and let CI regenerate it. -->",
        "",
        f"# {TITLES[site]}",
        "",
        INTROS[site],
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    for entry in entries:
        cells = [entry[f] or "-" for f in FIELDS]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="生成文档站的 EOL 页面")
    parser.add_argument("--check", action="store_true", help="只检查是否过期，不写文件")
    args = parser.parse_args()

    stale = False
    for site in SITES:
        try:
            content = render(site)
        except EolDataError as exc:
            print(f"[错误] {exc}", file=sys.stderr)
            return 2
        out = page_path(site)
        current = out.read_text(encoding="utf-8") if out.exists() else None
        rel = out.relative_to(REPO_ROOT).as_posix()
        if current == content:
            print(f"up to date  {rel}")
            continue
        if args.check:
            print(f"STALE       {rel}")
            stale = True
            continue
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote       {rel} ({len(content.splitlines())} lines)")

    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
