#!/usr/bin/env python3
"""为每个含 Manuals/ 的产品目录生成 .nav.yml，把导航里的 Manuals 层拍平。

    docs/<lang>/<产品>/Manuals/{安装指南,用户手册,...}  ->  导航直接显示子分类

生成的 .nav.yml 内容固定（见 CONTENT），对 awesome-nav 的语义：
  - "Manuals/*"  把 Manuals 的子目录按默认字母序提升到产品层（排在最前）
  - "*"          其余内容（Developer Documentation / Use Cases /
                 certifications.md / drawings.md 等）按默认字母序跟在后面
只影响导航显示，页面 URL 不变。

规则：
  - 只处理直接位于语言根下、含 Manuals/ 子目录的产品目录；
    没有 Manuals 的产品不写（awesome-nav 对空匹配的 glob 会报错）。
  - 已存在且不带 AUTO-GENERATED 标记的 .nav.yml 视为手工定制，跳过不动。
  - 幂等：内容一致则不重写；构建时生成，产品层 .nav.yml 不进 git
    （见 .gitignore，语言根的 docs/<lang>/.nav.yml 是手工维护的，不受影响）。

用法：
    python scripts/generate_nav_files.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LANGS = ("zh", "en")
MARKER = "AUTO-GENERATED by scripts/generate_nav_files.py"

CONTENT = f"""\
# {MARKER}; do not edit or commit.
# Flatten the Manuals level: its subcategories show directly under the product.
nav:
  - "Manuals/*"
  - "*"
"""


def main() -> int:
    wrote = skipped_custom = up_to_date = 0
    for lang in LANGS:
        lang_root = REPO_ROOT / "docs" / lang
        if not lang_root.is_dir():
            continue
        for product in sorted(lang_root.iterdir(), key=lambda p: p.as_posix()):
            if not product.is_dir() or not (product / "Manuals").is_dir():
                continue
            nav_file = product / ".nav.yml"
            if nav_file.exists():
                current = nav_file.read_text(encoding="utf-8")
                if MARKER not in current:
                    print(f"custom      {nav_file.relative_to(REPO_ROOT).as_posix()}")
                    skipped_custom += 1
                    continue
                if current == CONTENT:
                    up_to_date += 1
                    continue
            nav_file.write_text(CONTENT, encoding="utf-8", newline="\n")
            print(f"wrote       {nav_file.relative_to(REPO_ROOT).as_posix()}")
            wrote += 1
    print(f"nav files: {wrote} written, {up_to_date} up to date, "
          f"{skipped_custom} custom (skipped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
